version: '3.8'

services:
  analytics_workspace:
    build: .
    container_name: scr_analytics_env
    volumes:
      - .:/workspace
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0